import { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, WidthType, BorderStyle, AlignmentType } from "docx";
import { saveAs } from "file-saver";
import { MeetingData } from "../types";

export async function generateDOCX(data: MeetingData) {
  const border = { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" };
  const borders = { top: border, bottom: border, left: border, right: border };

  const sectionHeading = (text: string) => new Paragraph({
    children: [new TextRun({ text, bold: true, size: 24, color: "663399" })],
    spacing: { before: 400, after: 150 },
  });

  const makeRow = (num: string, label: string, value: string) => new TableRow({
    children: [
      new TableCell({
        children: [new Paragraph({ children: [new TextRun({ text: num, size: 18 })] })],
        width: { size: 500, type: WidthType.DXA },
        borders,
      }),
      new TableCell({
        children: [new Paragraph({ children: [new TextRun({ text: label, bold: true, size: 18 })] })],
        width: { size: 4000, type: WidthType.DXA },
        borders,
      }),
      new TableCell({
        children: [new Paragraph({ children: [new TextRun({ text: value || "—", size: 18 })] })],
        width: { size: 4500, type: WidthType.DXA },
        borders,
      }),
    ],
  });

  const doc = new Document({
    sections: [{
      children: [
        // Logo text
        new Paragraph({
          children: [new TextRun({ text: "mitoo", bold: true, size: 40, color: "663399" })],
          alignment: AlignmentType.CENTER,
          spacing: { after: 50 },
        }),
        new Paragraph({
          children: [new TextRun({ text: "CRM Solutions", size: 16, color: "888888" })],
          alignment: AlignmentType.CENTER,
          spacing: { after: 300 },
        }),

        // Title
        new Paragraph({
          children: [new TextRun({ text: "MINUTES OF MEETING", bold: true, size: 32 })],
          alignment: AlignmentType.CENTER,
          spacing: { after: 400 },
        }),

        // Meeting Details
        sectionHeading("Details of Meeting :-"),
        new Table({
          rows: [
            makeRow("1", "Participants (from our side)", data.participant),
            makeRow("2", "Time of meeting", data.meetingTime),
            makeRow("3", "Date of meeting", data.meetingDate),
          ],
          width: { size: 9000, type: WidthType.DXA },
        }),

        // Customer Details
        sectionHeading("Customers Details :-"),
        new Table({
          rows: [
            makeRow("1", "Company Name", data.companyName),
            makeRow("2", "Meeting with", data.meetingWith),
            makeRow("3", "Designation", data.designation),
            makeRow("4", "Industry", data.industry),
            makeRow("5", "Location", data.location),
            makeRow("6", "Total Number of Employees", data.totalEmployees),
            makeRow("7", "Currently Using", data.currentlyUsing),
            makeRow("8", "Other remarks", data.otherRemarks),
          ],
          width: { size: 9000, type: WidthType.DXA },
        }),

        // Points Discussed
        sectionHeading("Points Discussed :-"),
        new Paragraph({
          children: [new TextRun({ text: `Plan: ${data.plan}`, bold: true, size: 20 })],
          spacing: { after: 200 },
        }),
        new Table({
          rows: [
            makeRow("a", "Lead Creation", data.leadCreation),
            makeRow("b", "Lead Assignment", data.leadAssignment),
            makeRow("c", "Follow-up Management", data.followUpManagement),
            makeRow("d", "Customer Management", data.customerManagement),
            makeRow("e", "Quotation Management", data.quotationManagement),
            makeRow("f", "Task & Reminder Management", data.taskReminderManagement),
            makeRow("g", "Lead sources", data.leadSources),
            makeRow("h", "Follow-up process", data.followUpProcess),
            makeRow("i", "WhatsApp/Email integrations", data.whatsappEmailIntegration),
            makeRow("j", "Mobile app requirements", data.mobileAppRequirements),
            makeRow("k", "Reports & Dashboard", data.reportsDashboard),
            makeRow("l", "Data Migrations", data.dataMigrations),
            makeRow("m", "Customization requirements", data.customizationRequirements),
          ],
          width: { size: 9000, type: WidthType.DXA },
        }),

        // Next Steps
        new Paragraph({ spacing: { before: 400 }, children: [] }),
        new Table({
          rows: [
            makeRow("", "Next follow update", data.nextFollowUpDate),
            makeRow("", "Remarks", data.remarks),
          ],
          width: { size: 9000, type: WidthType.DXA },
        }),

        // Footer
        new Paragraph({
          children: [new TextRun({ text: "Generated by Mitoo MOM Generator", size: 14, color: "AAAAAA", italics: true })],
          alignment: AlignmentType.CENTER,
          spacing: { before: 600 },
        }),
      ],
    }],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `MOM-${data.companyName || "Meeting"}-${data.meetingDate}.docx`);
}
